# Site settings
title: Paper Theme
description: > # this means to ignore newlines until "baseurl:"
  A gentle theme for Jekyll utilising material design.
baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: pygments
gems: [jekyll-paginate]

# comments
disqus: # add disqus shortname here

# author info
# add your appropriate info here
author: # your name
bio:    # your bio
email:
email_md5: # md5 hash of your email
twitter_username:
github_username:

# Theming options
# These settings are mandatory.
theme:              'blue-pink'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
